app:
  port: "8080"
  environment: "production"

database:
  url: "postgres://postgres:postgres@localhost:5432/db_name?sslmode=disable"
  maxConnections: 10

jwt:
  secret: "your_jwt_secret_key"
  expiration: 3600 # 1 hour

auth:
  validFor: 120  # minutes

logging:
  level: "info"
  file: "app.log"
